### ISSUE TITLE
Template doesn't work in nativescript 6.2.0

### ISSUE THREAD

**Issue by uzarsalan** [halfnelson/svelte-native#98]
Template in listView doesn't work in nativescript 6.2.0
after "tns update"
```
Couldn't determine component to use for item at 299
```

**Comment by halfnelson** [comment]
Yikes!, I'll look into this asap

**Comment by halfnelson** [comment]
I have shipped svelte-native 0.7.0 that resolves this. I didn't make any changes to the svelte native code apart from compiling against the newer version of the core modules (even though they should be external), but confirmed the problem goes away.

**Comment by okrad** [comment]
Hi @halfnelson, 
with the newest svelte-native-template as of 20191124 I get this error building the todoapp:
```
TypeError: Object(...) is not a function
File: (file:///data/data/org.nativescript.preview/files/app/vendor.js:891:10)

StackTrace: 
c(file:///data/data/org.nativescript.preview/files/app/bundle.js:132:76)
	at init(file:///data/data/org.nativescript.preview/files/app/tns_modules/svelte/internal/index.js:1298:19)
	at App(file:///data/data/org.nativescript.preview/files/app/bundle.js:232:63)
	at createProxiedComponent(file:///data/data/org.nativescript.preview/files/app/vendor.js:1207:9)
	at ProxyComponent(file:///data/data/org.nativescript.preview/files/app/vendor.js:806:89)
	at Proxy<App>(file:///data/data/org.nativescript.preview/files/app/vendor.js:863:11)
	at resolveComponentElement(file:///data/data/org.nativescript.preview/files/app/tns_modules/svelte-native/dom/index.js:1279:22)
	at navigate(file:///data/data/org.nativescript.preview/files/app/tns_modules/svelte-native/dom/index.js:1292:35)
	at svelteNative(file:///data/data/org.nativescript.preview/files/app/tns_modules/svelte-native/index.js:38:26)
	at (file:///data/data/org.nativescript.preview/files/app/bundle.js:331:67)
	at ./app.ts(file:///data/data/org.nativescript.preview/files/app/bundle.js:344:30)
	at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:751:30)
	at checkDeferredModules(file:///data/data/org.nativescript.preview/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/org.nativescript.preview/files/app/runtime.js:31:19)
	at (file:///data/data/org.nativescript.preview/files/app/bundle.js:2:57)
	at require(:1:266)


TypeError: Object(...) is not a function
	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:674)
	at com.tns.Runtime.run(Runtime.java:666)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5954)
	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6815)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
Commenting out the Template tag the error disappears...

**Comment by halfnelson** [comment]
@okrad I am having trouble replicating the problem. I created a repo with the todoapp from the tutorial
https://github.com/halfnelson/svelte-native-todo-tutorial
and ran it with a fresh version of the template, it works as expected. Maybe it is something to do with your implementation?

**Comment by okrad** [comment]
Hi @halfnelson,
I'm just starting out with nativescript so I could be missing something...

I cloned the svelte-native-todo-tutorial repo, run npm install and then tns preview.

After scanning the QR code I get this error on the phone:

```
com.tns.NativeScriptException: Error calling module function TypeError: Object(...) is not a function
File: (file:///data/data/org.nativescript.preview/files/app/vendor.js:891:10)
StackTrace: c(file:///data/data/org.nativescript.preview/files/app/bundle.js:192:76)	
at init(file:///data/data/org.nativescript.preview/files/app/tns_modules/svelte/internal/index.js:1298:19)	
at App(file:///data/data/org.nativescript.preview/files/app/bundle.js:363:63)	
at createProxiedComponent(file:///data/data/org.nativescript.preview/files/app/vendor.js:1207:9)	
at ProxyComponent(file:///data/data/org.nativescript.preview/files/app/vendor.js:806:89)	
at Proxy<App>(file:///data/data/org.nativescript.preview/files/app/vendor.js:863:11)	
at resolveComponentElement(file:///data/data/org.nativescript.preview/files/app/tns_modules/svelte-native/dom/index.js:1279:22)	
at navigate(file:///data/data/org.nativescript.preview/files/app/tns_modules/svelte-native/dom/index.js:1292:35)	
at svelteNative(file:///data/data/org.nativescript.preview/files/app/tns_modules/svelte-native/index.js:38:26)	
at (file:///data/data/org.nativescript.preview/files/app/bundle.js:463:67)	
at ./app.ts(file:///data/data/org.nativescript.preview/files/app/bundle.js:476:30)	
at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:751:30)	
at checkDeferredModules(file:///data/data/org.nativescript.preview/files/app/runtime.js:44:23)	
at webpackJsonpCallback(file:///data/data/org.nativescript.preview/files/app/runtime.js:31:19)	
at (file:///data/data/org.nativescript.preview/files/app/bundle.js:2:57)	
at require(:1:266)

TypeError: Object(...) is not a function	
at com.tns.Runtime.runModule(Native Method)	
at com.tns.Runtime.runModule(Runtime.java:674)	
at com.tns.Runtime.run(Runtime.java:666)	
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)	
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)	
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5954)	
at android.app.ActivityThread.access$1200(ActivityThread.java:200)	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)	
at android.os.Handler.dispatchMessage(Handler.java:106)	
at android.os.Looper.loop(Looper.java:201)	
at android.app.ActivityThread.main(ActivityThread.java:6815)	
at java.lang.reflect.Method.invoke(Native Method)	
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
and in the terminal I get the same error as before.

I'm starting to believe it's a problem with my nativescript installation...

**Comment by halfnelson** [comment]
It could be, does tns --version say 6.2?

**Comment by okrad** [comment]
Kind of... It's 6.2.2...
Sorry, I didn't realize it before. Maybe I should downgrade to 6.2.0?

**Comment by halfnelson** [comment]
Nah, 6.2.2 should work. Does it work with tns run ?

**Comment by okrad** [comment]
Yes, it works both with the android emulator and with the actual phone... 
The only problem is in preview mode... I guess I'll just use "tns run" then...

**Comment by halfnelson** [comment]
Thanks for helping debug the issue. I don't usually use preview, the camera
on my phone can't focus so scanning the we code is a pain

**Comment by okrad** [comment]
Thank you for taking the time of looking into it!

**Comment by halfnelson** [comment]
I tried preview with latest version of the Nativescript Playground and Nativescript Preview apps on my phone and couldn't reproduce. If you update your Playground and Preview Apps and clone the latest todoapp repo do you still get the same behaviour?

**Comment by halfnelson** [comment]
I think this was finally resolved after managing to reproduce with latest nativescript. The latest version of the preview app combined with latest svelte-native (and updated webpack.config from the template) should fix this.

**Comment by okrad** [comment]
Sorry, I have been quite busy in recent days... 
I can confirm that the problem is fixed with the new version of nativescript.
